source = ./matugen-colors.conf

$font_family = Inter

animations {
    bezier = ease-in-out, 0.5, 0, 0.5, 1

    animation = inputFieldColors, 1, 2, ease-in-out
}

background {
    path = $image

    blur_passes = 3
    blur_size = 8
}

label {
    text = <b> </b>
    color = $primary
    font_size = 16

    position = 32, -32 # Padding[32], Padding[32]
    halign = left
    valign = top
}

label {
    text = <b>$USER</b>
    color = $on_surface
    font_size = 16
    font_family = $font_family

    position = 56, -32 # Padding[32] + User-icon:font_size[16] + Spacing[8], Padding[32]
    halign = left
    valign = top
}

label {
    text = cmd[update:1000] echo "$(uptime -p)"
    color = $on_surface_variant
    font_size = 14
    font_family = $font_family

    position = 32, -56 # Padding[32], Padding[32] + User:font_size[16] + Spacing[8]
    halign = left
    valign = top
}

label {
    text = <b>$TIME</b>
    color = $on_surface
    font_size = 64  # 16 * 4
    font_family = $font_family

    halign = center
    valign = center
}

input-field {
    size = 100%, 40

    outline_thickness = 0

    dots_size = 0.4
    dots_spacing = 0.4

    inner_color = rgba(00000000)

    font_color = $primary
    font_family = $font_family

    placeholder_text =

    check_color = rgba(00000000)
    fail_color = rgba(00000000)

    fail_text = <b>Wrong Password ($ATTEMPTS)</b>

    position = 0, -84 # 0, (Time:font_size[64] / 2) + (Height[40] / 2) + Spacing[32]
    halign = center
    valign = center
}

label {
    text = <b> </b>
    color = $primary
    font_size = 16

    position = 32, 32 # Padding[32], Padding[32]
    halign = left
    valign = bottom
}

label {
    text = cmd[update:1000] echo "$($HOME/.config/hypr/scripts/playerctl.sh)"
    color = $on_surface
    font_size = 16
    font_family = $font_family

    position = 56, 32 # Padding[32] + Play-icon:font_size[16] + Spacing[8], Padding[32]
    halign = left
    valign = bottom
}
